### ISSUE TITLE
Could not load nf-core/config profiles

### ISSUE THREAD

**Issue by chklopp** [marchoeppner/esga2#5]
### Description of the bug

When I launch the pipeline I get the following error 

cat nf.output
/var/spool/slurm/d/job35576642/slurm_script: ligne13: bioinfo/nfcore-Nextflow-v21.10.6: Aucun fichier ou dossier de ce type
N E X T F L O W  ~  version 0.17.3
Launching 'nf-core/genomeannotator' - revision: cbd878f799 [dev]
WARNING: Could not load nf-core/config profiles: https://raw.githubusercontent.com/nf-core/configs/master/nfcore_custom.config
Unknown configuration profile: 'genotoul'

Here is may command line : 
nextflow run nf-core/genomeannotator -r dev -profile genotoul --assemblyfirst_assembly.fasta --rnaseq_samples sample_sheet.csv --proteins proteins.fasta --outdir output --aug_species human

genotoul is one of the profiles found in https://raw.githubusercontent.com/nf-core/configs/master/nfcore_custom.config

### Command used and terminal output

```console
command used :
nextflow run nf-core/genomeannotator -r dev -profile genotoul --assemblyfirst_assembly.fasta --rnaseq_samples sample_sheet.csv 


cat .nextflow.log
juil.-15 10:30:04.213 [main] DEBUG nextflow.cli.Launcher - $> /home/klopp/save/bin/nextflow run nf-core/genomeannotator -r dev -profile genotoul --assembly Cyathomix_first_assembly.fasta --rnaseq_samples sample_sheet.csv --proteins proteins.fasta --outdir output --aug_species caenorhabditis
juil.-15 10:30:04.275 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 0.17.3
juil.-15 10:30:04.911 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/klopp/.nextflow/assets/nf-core/genomeannotator/.git/config; branch: master; remote: origin; url: https://github.com/nf-core/genomeannotator.git
juil.-15 10:30:05.094 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/klopp/.nextflow/assets/nf-core/genomeannotator/.git/config; branch: master; remote: origin; url: https://github.com/nf-core/genomeannotator.git
juil.-15 10:30:05.777 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/klopp/.nextflow/assets/nf-core/genomeannotator/.git/config; branch: master; remote: origin; url: https://github.com/nf-core/genomeannotator.git
juil.-15 10:30:05.777 [main] INFO  nextflow.cli.CmdRun - Launching 'nf-core/genomeannotator' - revision: cbd878f799 [dev]
juil.-15 10:30:05.790 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /home/klopp/.nextflow/assets/nf-core/genomeannotator/nextflow.config
juil.-15 10:30:05.792 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/klopp/.nextflow/assets/nf-core/genomeannotator/nextflow.config
juil.-15 10:30:05.918 [main] DEBUG nextflow.config.ConfigBuilder - Setting config profile: 'genotoul'
juil.-15 10:30:06.338 [main] DEBUG nextflow.cli.Launcher - Operation aborted
nextflow.exception.AbortOperationException: Unknown configuration profile: 'genotoul'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at nextflow.config.ConfigBuilder.checkValidProfile(ConfigBuilder.groovy:309)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at nextflow.config.ConfigBuilder.buildConfig0(ConfigBuilder.groovy:285)
	at nextflow.config.ConfigBuilder$buildConfig0$2.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
	at nextflow.config.ConfigBuilder.buildConfig(ConfigBuilder.groovy:235)
	at nextflow.config.ConfigBuilder$buildConfig$1.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at nextflow.config.ConfigBuilder.build(ConfigBuilder.groovy:460)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:175)
	at nextflow.cli.Launcher.run(Launcher.groovy:380)
	at nextflow.cli.Launcher.main(Launcher.groovy:529)
```

### System information

nfcore-Nextflow-v21.10.6
HPC
slurm

**Comment by marchoeppner** [comment]
Hi, sorry for the late response (didn't get a notification..). 

A few things to check:

- Could you run this from my dev fork? The main repo is a bit behind until I have fixed some of the linting requirements:
nextflow run marchoeppner/genomeannotator -r dev <...>
- Your nextflow version is very, very outdated. Could you update to a more recent version? https://github.com/nextflow-io/nextflow/releases
- Do any of the other nf-core pipelines work for you?

Cheers,
M

**Comment by Rajarshi0** [comment]
Getting the same issues for WSL Ubuntu: 

Issue:
WARNING: Could not load nf-core/config profiles: https://raw.githubusercontent.com/nf-core/configs/master/nfcore_custom.config
